export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const MAKE_ITEM_CHECKED = "MAKE_ITEM_CHECKED";
export const SHOW_ITEMS_FOR_CURRENT_AREA = "SHOW_ITEMS_FOR_CURRENT_AREA";
export const SET_SEARCHED_WORD = "SET_SEARCHED_WORD";
